name: genmon4
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.31.0
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/sounds/

flutter_native_splash:
  color: "#000000"
  image: assets/splash_icon.png # (add your logo here if you have one)
  android: true
  ios: true
  web: false 